name: Build HMM Demo (Windows)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'nouse'
        required: false
        default: 'nouse'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup vcpkg and install dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          git checkout 2025.07.25
          cd ..
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install --triplet x86-windows
          ./vcpkg/vcpkg integrate install

      - name: Configure CMake
        run: |
          # Configure the CMake project.  The -A Win32 argument selects a 32‑bit
          # build on Windows.  The MLpack source directory and vcpkg toolchain
          # file are provided so that CMake can locate the library source and
          # installed dependencies.  The VCPKG_TARGET_TRIPLET is set to match
          # the installed dependencies.
          cmake -S . -B build -A Win32 \
            -DMLPACK_SRC_DIR="$GITHUB_WORKSPACE/mlpack" \
            -DCMAKE_TOOLCHAIN_FILE="$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake" \
            -DVCPKG_TARGET_TRIPLET=x86-windows \
            -DMLPACK_BUILD_TESTS=OFF -DMLPACK_BUILD_BENCHMARKS=OFF

      - name: Build
        run: |
          # Build the demo in Release mode.  The --parallel flag speeds up
          # compilation by using all available cores.
          cmake --build build --config Release --parallel
