name: Build HMM Demo (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Specify the mlpack version tag to check out.  This matches the
  # release used in the README.
  MLPACK_VERSION: 4.6.2

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup vcpkg and install dependencies
        run: |
          git clone --depth 1 https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
          ./vcpkg/vcpkg install --triplet x86-windows

      - name: Clone mlpack source
        run: |
          git clone --depth 1 --branch ${MLPACK_VERSION} https://github.com/mlpack/mlpack.git mlpack

      - name: Configure CMake
        run: |
          cmake -S . -B build -A Win32 \
            -DMLPACK_SRC_DIR="$GITHUB_WORKSPACE/mlpack" \
            -DCMAKE_TOOLCHAIN_FILE="$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake" \
            -DMLPACK_BUILD_TESTS=OFF -DMLPACK_BUILD_BENCHMARKS=OFF

      - name: Build
        run: cmake --build build --config Release --parallel
